import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Random;


public class CPUPlayer extends player {

  //Fields

  //Methods

  public int CPUChoice(int[] list){ //returns a random number that a CPU player can use. The argument passed through is a list of filled coloumns generated by the checkSpace() method in the newBoard class
    
  Random rand = new Random();

  int random = rand.nextInt(7);

  for (int ex : list){

    if(random == ex){

      random++;

    }

  }

  return random;

  }; 

//Constructor

public CPUPlayer(char counterColour, boolean hasWon){
  super(counterColour, hasWon);

  this.counterColour = counterColour;
  this.hasWon = hasWon;

}

}

